---
server:
    install: '1'
    packages: [vim, git, htop, nodejs, npm]
    timezone: UTC
    locale: pt_BR.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.33.99, memory: '512', sharedfolder: ./src, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /src/public
    servername: dev.dev
mysql:
    install: '1'
    root_password: root
    database: otzy
    user: admin
    password: admin
    dump: ''
mongodb:
    install: '1'
redis:
    install: '1'
    port: '6379'
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-curl, php5-mysql, php5-mongo]
xdebug:
    install: '1'
composer:
    install: '1'

